/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Passport } from "./Passport";
export * as factories from "./factories";
export { Passport__factory } from "./factories/Passport__factory";
